package com.cloudsentinel.dto;

/**
 * Data Transfer Object capturing AI model usage metrics and performance statistics for a single AI invocation.
 *
 * <p>Each time the system calls an AI model (Ollama or AWS Bedrock) to analyze cloud resources,
 * this record captures the token usage breakdown, timing information, character counts, throughput,
 * and a whimsical "fun fact" comment about the AI's performance. This data is displayed in the
 * UI alongside AI insights and is useful for monitoring AI cost and performance across scans.</p>
 *
 * <p>This record is embedded within {@link AiInsightDto} and is included in the serialized
 * {@link AnalysisResponse} and cached {@link ScanReportDto}.</p>
 *
 * <p>Serialized to JSON using the global Jackson {@code SNAKE_CASE} naming strategy, producing
 * field names such as {@code prompt_tokens}, {@code completion_tokens}, {@code tokens_per_second},
 * and {@code fun_fact}.</p>
 *
 * <p>As a Java {@code record}, instances are immutable. Two factory methods are provided:
 * {@link #empty()} for fallback scenarios and {@link #of} for normal construction with
 * automatic throughput calculation and fun fact generation.</p>
 *
 * @param provider            the AI provider name (e.g., "ollama" or "bedrock")
 * @param model               the specific model identifier (e.g., "llama3.2", "claude-sonnet")
 * @param promptTokens        the number of tokens in the prompt sent to the AI, or {@code null} if unavailable
 * @param completionTokens    the number of tokens generated by the AI in its response, or {@code null} if unavailable
 * @param totalTokens         the sum of prompt and completion tokens, or {@code null} if unavailable
 * @param durationMs          the wall-clock duration of the AI call in milliseconds
 * @param promptCharacters    the character count of the prompt text sent to the AI
 * @param responseCharacters  the character count of the AI's response text
 * @param tokensPerSecond     the computed throughput of the AI response generation (completion tokens per second),
 *                            rounded to one decimal place
 * @param funFact             a humorous, human-readable comment about the AI's performance characteristics
 *
 * @see AiInsightDto
 */
public record AiUsageDto(
        String provider,
        String model,
        Integer promptTokens,
        Integer completionTokens,
        Integer totalTokens,
        long durationMs,
        int promptCharacters,
        int responseCharacters,
        double tokensPerSecond,
        String funFact
) {
    /**
     * Creates an empty {@code AiUsageDto} with all fields set to zero or {@code null}.
     *
     * <p>Used as a fallback when AI usage metrics are unavailable, such as when the AI
     * call fails or when no AI analysis was performed.</p>
     *
     * @return an {@code AiUsageDto} with zeroed metrics and {@code null} provider/model/funFact
     */
    public static AiUsageDto empty() {
        return new AiUsageDto(null, null, null, null, null, 0, 0, 0, 0, null);
    }

    /**
     * Creates an {@code AiUsageDto} with the given metrics, automatically computing tokens-per-second
     * throughput and generating a fun fact based on the performance characteristics.
     *
     * <p>The tokens-per-second value is calculated as {@code completionTokens / (durationMs / 1000.0)}
     * when both values are positive, and is rounded to one decimal place. If completion tokens are
     * {@code null}, zero, or the duration is zero, throughput defaults to 0.</p>
     *
     * @param provider         the AI provider name (e.g., "ollama" or "bedrock")
     * @param model            the specific model identifier
     * @param promptTokens     the number of tokens in the prompt, or {@code null} if unavailable
     * @param completionTokens the number of tokens in the AI response, or {@code null} if unavailable
     * @param totalTokens      the total token count, or {@code null} if unavailable
     * @param durationMs       the wall-clock duration of the AI call in milliseconds
     * @param promptChars      the character count of the prompt text
     * @param responseChars    the character count of the AI response text
     * @return an {@code AiUsageDto} populated with the given metrics, computed throughput, and a fun fact
     */
    public static AiUsageDto of(String provider, String model,
                                 Integer promptTokens, Integer completionTokens, Integer totalTokens,
                                 long durationMs, int promptChars, int responseChars) {
        double tps = (completionTokens != null && completionTokens > 0 && durationMs > 0)
                ? completionTokens / (durationMs / 1000.0)
                : 0;
        String funFact = generateFunFact(totalTokens, durationMs, promptChars, responseChars, tps);
        return new AiUsageDto(provider, model, promptTokens, completionTokens, totalTokens,
                durationMs, promptChars, responseChars, Math.round(tps * 10.0) / 10.0, funFact);
    }

    /**
     * Estimates the dollar cost of this AI invocation based on provider and token counts.
     *
     * <p>Ollama (local) is free. Bedrock Claude pricing (approximate, as of 2025):</p>
     * <ul>
     *   <li>Claude Sonnet: $3/1M input tokens, $15/1M output tokens</li>
     *   <li>Claude Haiku: $0.25/1M input tokens, $1.25/1M output tokens</li>
     * </ul>
     *
     * @return estimated cost in USD, or 0.0 if provider is local or tokens are unavailable
     */
    public double estimatedCostUsd() {
        if (provider == null || "ollama".equalsIgnoreCase(provider)) return 0.0;
        int inTokens = promptTokens != null ? promptTokens : 0;
        int outTokens = completionTokens != null ? completionTokens : 0;
        if (model != null && model.contains("haiku")) {
            return (inTokens * 0.25 + outTokens * 1.25) / 1_000_000.0;
        }
        // Default to Sonnet pricing
        return (inTokens * 3.0 + outTokens * 15.0) / 1_000_000.0;
    }

    /**
     * Generates a humorous, human-readable "fun fact" comment based on the AI's performance characteristics.
     *
     * <p>The fun fact is selected based on a priority cascade of conditions:
     * <ol>
     *   <li>If total tokens are {@code null} or zero, returns a generic mystery message.</li>
     *   <li>If tokens-per-second exceeds 100, 50, or 20, returns a speed-themed message.</li>
     *   <li>If TPS is positive but below 20, returns a "deep thinking" message.</li>
     *   <li>If duration exceeds 2 minutes or 1 minute, returns a duration-themed message.</li>
     *   <li>If total tokens exceed 3000, returns a volume-themed message.</li>
     *   <li>If prompt characters exceed 10000, returns a prompt-size-themed message.</li>
     *   <li>Otherwise, returns a generic cheerful fallback message.</li>
     * </ol>
     *
     * @param totalTokens   the total token count, or {@code null} if unavailable
     * @param durationMs    the wall-clock duration of the AI call in milliseconds
     * @param promptChars   the character count of the prompt text
     * @param responseChars the character count of the AI response text (currently unused in selection logic)
     * @param tps           the computed tokens-per-second throughput
     * @return a fun fact string describing the AI's performance in a lighthearted manner
     */
    private static String generateFunFact(Integer totalTokens, long durationMs, int promptChars, int responseChars, double tps) {
        if (totalTokens == null || totalTokens == 0) return "The AI worked in mysterious ways this time.";

        if (tps > 100) return "Blazing fast! This AI was typing faster than a caffeinated squirrel.";
        if (tps > 50) return "Speed demon! The AI cranked through tokens like a hot knife through butter.";
        if (tps > 20) return "Steady and strong - the AI kept a solid pace throughout.";
        if (tps > 0) return "The AI took its time to think deeply about your cloud resources.";

        if (durationMs > 120_000) return "The AI really pondered this one - a 2+ minute meditation on your infrastructure.";
        if (durationMs > 60_000) return "A full minute of AI contemplation for your cloud estate.";
        if (totalTokens > 3000) return "A novel-length analysis! The AI had a lot to say about your resources.";
        if (promptChars > 10000) return "You fed the AI a hefty prompt - it digested all that cloud data like a champ.";

        return "Another day, another cloud analysed by your friendly AI assistant.";
    }
}
